var ANCHOR = window.location.hash || '';
var CDNS = {
	'dev': 'https://s3-us-west-1.amazonaws.com/moevideobucket/alfaphase2b/',
	'prod-nefta': 'http://www.alfaromeousa.com/ar_nafta/videos/videosync/',
	'prod-emea': 'http://www.alfaromeo.com/NS_Video_Content_AR/videos/videosync/'
};

var ENVIRONMENT = Utilities.getEnvironment();

var CONFIG = {
	"App": {
		"DEBUG": ENVIRONMENT == 'dev' || ANCHOR.indexOf('#debug') > -1 ? true : false,
		// "MOBILE": (ANCHOR.indexOf('#mobile') > -1) || is_explorer || is_edge ? true : false,
		"MOBILE": (ANCHOR.indexOf('#mobile') > -1) ? true : false,
		"USE_YOUTUBE": true,
		"CDN": CDNS[ENVIRONMENT],
		"YOUTUBE_PREFIX": "https://youtu.be/",
		"ClientLanguage": Utilities.getLanguage() || "english",
		"LogURL": "http://diocletian.local/ag_logger.php",
		// "VideoExtension": (Modernizr.video.webm && !is_explorer && !is_edge) ? "webm" : "mp4"
		"VideoExtension": (Modernizr.video.webm) ? "webm" : "mp4"
	},

	"VideoData": {
		"color": null,
		"wcolor": null,
		"wheel": null,
		"caliper": null
	},

	"Folders": {
		"Desktop": {
			"launch_videos": "launch_videos",
			"colorizer": "colorizer",
			"deep_dives": "deep_dives",
			"visualizer": "visualizer"
		},
		"Mobile": {
			"colorizer": "colorizer_mobile",
			"deep_dives": "deep_dives_mobile",
			"visualizer": "visualizer_mobile"
		}
	},

	"Youtube": {
		"90snoneinteractive": "RJ208IX1LcE",
		"rossoalfa": "jnk7qhbvCG4",
		"silverstonegraymetallic": "DDmckOkvb44",
		"vesuviograymetallic": "Dj0UiZe7uU8",
		"vulcanoblackmetallic": "6v40XahLjBs",
		"montecarlobluemetallic": "sSJLFmH7qO8",
		"trofeowhitetricoat": "OGmfX2esG-I",
		"rossocompetizionetricoat": "cpQPIBB_WMY",
		"splitter_englishcallouts": "uf9LFHQ9C6c",
		"engine_englishcallouts": "dKwlAw7H6yE",
		"carbonfiber_englishcallouts": "JKRIK_scz1s",
		"rossoalfa_tecnico_dark_red_day": "rpecAwNz2GQ",
		"rossoalfa_tecnico_dark_red_night": "_FunzYsxH3U",
		"rossoalfa_tecnico_dark_black_day": "vgKAOPf4x-8",
		"rossoalfa_tecnico_dark_black_night": "a_crFiRbPg4",
		"rossoalfa_tecnico_dark_yellow_day": "RmloTztEDl4",
		"rossoalfa_tecnico_dark_yellow_night": "gLh6V7f_LEw",
		"rossoalfa_tecnico_light_red_day": "PPlifZbtQ18",
		"rossoalfa_tecnico_light_red_night": "jIqV0BlcYFg",
		"rossoalfa_tecnico_light_black_day": "rIxWWtOtlPc",
		"rossoalfa_tecnico_light_black_night": "Eq63-f9wu4k",
		"rossoalfa_tecnico_light_yellow_day": "j_NnSWps4yQ",
		"rossoalfa_tecnico_light_yellow_night": "eatrsDyA-NY",
		"rossoalfa_5hole_dark_red_day": "I-RktaibR4w",
		"rossoalfa_5hole_dark_red_night": "Lln9L8Me-xU",
		"rossoalfa_5hole_dark_black_day": "04hYWKb8eY4",
		"rossoalfa_5hole_dark_black_night": "3tpajUy6mu0",
		"rossoalfa_5hole_dark_yellow_day": "RmGQeYHESWI",
		"rossoalfa_5hole_dark_yellow_night": "ZK6qtipbrOg",
		"rossoalfa_5hole_light_red_day": "Xx8ZgokQ2zw",
		"rossoalfa_5hole_light_red_night": "5Hz3IwbIA8k",
		"rossoalfa_5hole_light_black_day": "0XZMVPLpkxA",
		"rossoalfa_5hole_light_black_night": "2Z5hxZTc95M",
		"rossoalfa_5hole_light_yellow_day": "aPWPZPdzRUo",
		"rossoalfa_5hole_light_yellow_night": "qzyUr4grRG8",
		"montecarlobluemetallic_tecnico_dark_red_day": "n_63LVonYqA",
		"montecarlobluemetallic_tecnico_dark_red_night": "a_TmiR4PdY4",
		"montecarlobluemetallic_tecnico_dark_black_day": "s0CWthabLO0",
		"montecarlobluemetallic_tecnico_dark_black_night": "Gw9F0RSRkwY",
		"montecarlobluemetallic_tecnico_dark_yellow_day": "rj1QfseSLtM",
		"montecarlobluemetallic_tecnico_dark_yellow_night": "qZ-8aZ-C3YE",
		"montecarlobluemetallic_tecnico_light_red_day": "6Y609s3LTQ8",
		"montecarlobluemetallic_tecnico_light_red_night": "k-RE4rb5238",
		"montecarlobluemetallic_tecnico_light_black_day": "hX-QhVPz6N4",
		"montecarlobluemetallic_tecnico_light_black_night": "GVoQccwidUA",
		"montecarlobluemetallic_tecnico_light_yellow_day": "ogDDUkR12iY",
		"montecarlobluemetallic_tecnico_light_yellow_night": "tQBGL4b1EX4",
		"montecarlobluemetallic_5hole_dark_red_day": "WvgOLTAD6nw",
		"montecarlobluemetallic_5hole_dark_red_night": "-6LohAwtODE",
		"montecarlobluemetallic_5hole_dark_black_day": "SiaFwcbHCHg",
		"montecarlobluemetallic_5hole_dark_black_night": "vYI2mcF2VQM",
		"montecarlobluemetallic_5hole_dark_yellow_day": "IXhraUNo-F8",
		"montecarlobluemetallic_5hole_dark_yellow_night": "vrLZojyT6wo",
		"montecarlobluemetallic_5hole_light_red_day": "bbc4pGS8TNQ",
		"montecarlobluemetallic_5hole_light_red_night": "qnZJ4kPilNc",
		"montecarlobluemetallic_5hole_light_black_day": "qf3wy8qLIa8",
		"montecarlobluemetallic_5hole_light_black_night": "9b8R6vDc9Pw",
		"montecarlobluemetallic_5hole_light_yellow_day": "nrfG9DKbV9A",
		"montecarlobluemetallic_5hole_light_yellow_night": "YTKm6Q42AVY",
		"silverstonegraymetallic_tecnico_dark_red_day": "3bUXuRfVYSY",
		"silverstonegraymetallic_tecnico_dark_red_night": "FKlJ0K2LAfM",
		"silverstonegraymetallic_tecnico_dark_black_day": "L9WQ44saYdU",
		"silverstonegraymetallic_tecnico_dark_black_night": "Zy9PNLIl5Bg",
		"silverstonegraymetallic_tecnico_dark_yellow_day": "XYnrZeQeai8",
		"silverstonegraymetallic_tecnico_dark_yellow_night": "SxQ_JOdmkXA",
		"silverstonegraymetallic_tecnico_light_red_day": "WJTYL3S5mxA",
		"silverstonegraymetallic_tecnico_light_red_night": "kjLmj0La4Zo",
		"silverstonegraymetallic_tecnico_light_black_day": "-TC7Tsi2YQI",
		"silverstonegraymetallic_tecnico_light_black_night": "DuwIF7f3hm8",
		"silverstonegraymetallic_tecnico_light_yellow_day": "UV4Pz_7F2iM",
		"silverstonegraymetallic_tecnico_light_yellow_night": "N1HCqQ6UbCU",
		"silverstonegraymetallic_5hole_dark_red_day": "ps6_iECTCpw",
		"silverstonegraymetallic_5hole_dark_red_night": "K35iI65VApU",
		"silverstonegraymetallic_5hole_dark_black_day": "ey8rI7TrMkE",
		"silverstonegraymetallic_5hole_dark_black_night": "VSjNBRordzE",
		"silverstonegraymetallic_5hole_dark_yellow_day": "7RFH2Rcd5yY",
		"silverstonegraymetallic_5hole_dark_yellow_night": "XWYgH7HYrTg",
		"silverstonegraymetallic_5hole_light_red_day": "0rKLw05iuTo",
		"silverstonegraymetallic_5hole_light_red_night": "CTnFD8OEpjo",
		"silverstonegraymetallic_5hole_light_black_day": "kAZPEdGz_44",
		"silverstonegraymetallic_5hole_light_black_night": "HW9WjA-lTJU",
		"silverstonegraymetallic_5hole_light_yellow_day": "E0HNbi0fxk8",
		"silverstonegraymetallic_5hole_light_yellow_night": "L_ge8GONGCQ",
		"vesuviograymetallic_tecnico_dark_red_day": "sW9bwHT67_s",
		"vesuviograymetallic_tecnico_dark_red_night": "CS_BncIkk0A",
		"vesuviograymetallic_tecnico_dark_black_day": "PMe7tMMibyw",
		"vesuviograymetallic_tecnico_dark_black_night": "uXqD3kx2HIw",
		"vesuviograymetallic_tecnico_dark_yellow_day": "QhNLgYlTtGw",
		"vesuviograymetallic_tecnico_dark_yellow_night": "buMBkPhIcJA",
		"vesuviograymetallic_tecnico_light_red_day": "VBJGBYUoEdg",
		"vesuviograymetallic_tecnico_light_red_night": "j9JtCLxnRaM",
		"vesuviograymetallic_tecnico_light_black_day": "sUSuFh8Lfoo",
		"vesuviograymetallic_tecnico_light_black_night": "2H9zFSTGeKo",
		"vesuviograymetallic_tecnico_light_yellow_day": "03MIMyvP0X8",
		"vesuviograymetallic_tecnico_light_yellow_night": "DtaZ1aUYT3E",
		"vesuviograymetallic_5hole_dark_red_day": "tmxyHnRAt9A",
		"vesuviograymetallic_5hole_dark_red_night": "cLlhGhzzlVc",
		"vesuviograymetallic_5hole_dark_black_day": "9oCBm_MtIho",
		"vesuviograymetallic_5hole_dark_black_night": "rWF0Ldr7jKM",
		"vesuviograymetallic_5hole_dark_yellow_day": "BJQnFjpwmmA",
		"vesuviograymetallic_5hole_dark_yellow_night": "AVJaQI0fbVE",
		"vesuviograymetallic_5hole_light_red_day": "wrZ-hpVytwI",
		"vesuviograymetallic_5hole_light_red_night": "aVzj259jmkc",
		"vesuviograymetallic_5hole_light_black_day": "lVa5-hmI5ZI",
		"vesuviograymetallic_5hole_light_black_night": "s3SOMEmLlP4",
		"vesuviograymetallic_5hole_light_yellow_day": "YCH9ZT-8i-s",
		"vesuviograymetallic_5hole_light_yellow_night": "oFG8oG_5EHI",
		"vulcanoblackmetallic_tecnico_dark_red_day": "_GsPvBjkXXo",
		"vulcanoblackmetallic_tecnico_dark_red_night": "nvvQiinA9hU",
		"vulcanoblackmetallic_tecnico_dark_black_day": "233gZX1vl_8",
		"vulcanoblackmetallic_tecnico_dark_black_night": "rKBpoxKgMUg",
		"vulcanoblackmetallic_tecnico_dark_yellow_day": "pOLGVcZuUJ8",
		"vulcanoblackmetallic_tecnico_dark_yellow_night": "4_K19d2HQ7w",
		"vulcanoblackmetallic_tecnico_light_red_day": "_vLJCqjncR0",
		"vulcanoblackmetallic_tecnico_light_red_night": "5-aU0cvQ-1I",
		"vulcanoblackmetallic_tecnico_light_black_day": "ouxbcUvJANw",
		"vulcanoblackmetallic_tecnico_light_black_night": "XQDEPTIeUf4",
		"vulcanoblackmetallic_tecnico_light_yellow_day": "P_2E3XEVxp8",
		"vulcanoblackmetallic_tecnico_light_yellow_night": "XjFOuWtprvs",
		"vulcanoblackmetallic_5hole_dark_red_day": "pLICp2FePBE",
		"vulcanoblackmetallic_5hole_dark_red_night": "Jg5Nll8GUgY",
		"vulcanoblackmetallic_5hole_dark_black_day": "tucwGs2BHxs",
		"vulcanoblackmetallic_5hole_dark_black_night": "EAIewzzNZiU",
		"vulcanoblackmetallic_5hole_dark_yellow_day": "q3jxgip69kg",
		"vulcanoblackmetallic_5hole_dark_yellow_night": "VpvWUVcYnW0",
		"vulcanoblackmetallic_5hole_light_red_day": "5tpIQMb2bxw",
		"vulcanoblackmetallic_5hole_light_red_night": "6GncfxoZxNg",
		"vulcanoblackmetallic_5hole_light_black_day": "a7yA7vxHMTg",
		"vulcanoblackmetallic_5hole_light_black_night": "RpDL-Ap_2E0",
		"vulcanoblackmetallic_5hole_light_yellow_day": "G7YUNUy3Gng",
		"vulcanoblackmetallic_5hole_light_yellow_night": "sHUq49R_pO8",
		"trofeowhitetricoat_tecnico_dark_red_day": "kzNl94VL-0g",
		"trofeowhitetricoat_tecnico_dark_red_night": "7h_sR0mje_s",
		"trofeowhitetricoat_tecnico_dark_black_day": "omy7-hoq3sw",
		"trofeowhitetricoat_tecnico_dark_black_night": "ft4ObvvM7hY",
		"trofeowhitetricoat_tecnico_dark_yellow_day": "aa2K1aywUkc",
		"trofeowhitetricoat_tecnico_dark_yellow_night": "qczcwyxhPOs",
		"trofeowhitetricoat_tecnico_light_red_day": "i0LCt5-gfVw",
		"trofeowhitetricoat_tecnico_light_red_night": "z1eymKnE1bo",
		"trofeowhitetricoat_tecnico_light_black_day": "5NFxps3VFO8",
		"trofeowhitetricoat_tecnico_light_black_night": "8ZKZP0eKS_E",
		"trofeowhitetricoat_tecnico_light_yellow_day": "5l6DYhUcVow",
		"trofeowhitetricoat_tecnico_light_yellow_night": "_LWKSpwa6wM",
		"trofeowhitetricoat_5hole_dark_red_day": "a3uC-fngnks",
		"trofeowhitetricoat_5hole_dark_red_night": "MboexGoolTM",
		"trofeowhitetricoat_5hole_dark_black_day": "NUCKU3QBuxc",
		"trofeowhitetricoat_5hole_dark_black_night": "gwan2dtKGcw",
		"trofeowhitetricoat_5hole_dark_yellow_day": "26Cvz9OwaB8",
		"trofeowhitetricoat_5hole_dark_yellow_night": "ipDz2iprhmc",
		"trofeowhitetricoat_5hole_light_red_day": "okZ9WMU4H7o",
		"trofeowhitetricoat_5hole_light_red_night": "dlOQK1CGToc",
		"trofeowhitetricoat_5hole_light_black_day": "tLqRtHoiyfA",
		"trofeowhitetricoat_5hole_light_black_night": "vwc2akX3I9k",
		"trofeowhitetricoat_5hole_light_yellow_day": "ug18Ua8dutY",
		"trofeowhitetricoat_5hole_light_yellow_night": "WRJZvKc6IJs",
		"rossocompetizionetricoat_tecnico_dark_red_day": "zdFMnMxuJ0A",
		"rossocompetizionetricoat_tecnico_dark_red_night": "gmtdyHvXYdE",
		"rossocompetizionetricoat_tecnico_dark_black_day": "Kxj4mrtUZd4",
		"rossocompetizionetricoat_tecnico_dark_black_night": "1044jdSErLM",
		"rossocompetizionetricoat_tecnico_dark_yellow_day": "-8tQQJRQmdg",
		"rossocompetizionetricoat_tecnico_dark_yellow_night": "y-HEz5smGxU",
		"rossocompetizionetricoat_tecnico_light_red_day": "X0P89vv-vOY",
		"rossocompetizionetricoat_tecnico_light_red_night": "7SLkOo3l8nQ",
		"rossocompetizionetricoat_tecnico_light_black_day": "D6IZZFScLJ0",
		"rossocompetizionetricoat_tecnico_light_black_night": "mQiI-Egb1FY",
		"rossocompetizionetricoat_tecnico_light_yellow_day": "xfU8SqLyCDI",
		"rossocompetizionetricoat_tecnico_light_yellow_night": "KRPovwDMOts",
		"rossocompetizionetricoat_5hole_dark_red_day": "Zv_mePTyrA4",
		"rossocompetizionetricoat_5hole_dark_red_night": "8_gX6iJ36ZA",
		"rossocompetizionetricoat_5hole_dark_black_day": "7cTwfA926KE",
		"rossocompetizionetricoat_5hole_dark_black_night": "-Cl0RYUAMgQ",
		"rossocompetizionetricoat_5hole_dark_yellow_day": "xOcmKw5E28k",
		"rossocompetizionetricoat_5hole_dark_yellow_night": "rX-WLLBSoag",
		"rossocompetizionetricoat_5hole_light_red_day": "UzZxqFMbYYU",
		"rossocompetizionetricoat_5hole_light_red_night": "7Nd0wpXMaIY",
		"rossocompetizionetricoat_5hole_light_black_day": "DCAHCIsODuk",
		"rossocompetizionetricoat_5hole_light_black_night": "2XkyxN-fYDU",
		"rossocompetizionetricoat_5hole_light_yellow_day": "YeeMrM2kX6w",
		"rossocompetizionetricoat_5hole_light_yellow_night": "1ippDKY15pM",
		"rossoalfa_tecnico_dark_red_m": "oQ63SNKB4z8",
		"rossoalfa_tecnico_dark_black_m": "QrgB6zv_wuo",
		"rossoalfa_tecnico_dark_yellow_m": "uIgCrNX2m8Q",
		"rossoalfa_tecnico_light_red_m": "5AoOFZZh76E",
		"rossoalfa_tecnico_light_black_m": "bUGxE0Kv8Wo",
		"rossoalfa_tecnico_light_yellow_m": "EcHeFUhpNJo",
		"rossoalfa_5hole_dark_red_m": "ADI2ANTMR4c",
		"rossoalfa_5hole_dark_black_m": "xBRRKOctkKY",
		"rossoalfa_5hole_dark_yellow_m": "4DWisH2QC40",
		"rossoalfa_5hole_light_red_m": "59xb9PDbTYw",
		"rossoalfa_5hole_light_black_m": "v1dDkksnuIw",
		"rossoalfa_5hole_light_yellow_m": "H-Nss7smixs",
		"montecarlobluemetallic_tecnico_dark_red_m": "2pNWD2q6pXQ",
		"montecarlobluemetallic_tecnico_dark_black_m": "SGDnemhpsZQ",
		"montecarlobluemetallic_tecnico_dark_yellow_m": "U8Bc9qNJAGs",
		"montecarlobluemetallic_tecnico_light_red_m": "6nUugiweBks",
		"montecarlobluemetallic_tecnico_light_black_m": "ug0gWV3lvmk",
		"montecarlobluemetallic_tecnico_light_yellow_m": "HqioQcs2rDU",
		"montecarlobluemetallic_5hole_dark_red_m": "JMG6AdovMYk",
		"montecarlobluemetallic_5hole_dark_black_m": "YfxIzgwtYfA",
		"montecarlobluemetallic_5hole_dark_yellow_m": "B415p189vUU",
		"montecarlobluemetallic_5hole_light_red_m": "nQYZtHBTmsE",
		"montecarlobluemetallic_5hole_light_black_m": "jOFCJ2tLRng",
		"montecarlobluemetallic_5hole_light_yellow_m": "CBJ2aM2u0HM",
		"silverstonegraymetallic_tecnico_dark_red_m": "tP3DgvA5_us",
		"silverstonegraymetallic_tecnico_dark_black_m": "PpAnuKHs62E",
		"silverstonegraymetallic_tecnico_dark_yellow_m": "Mywgk_8-c5s",
		"silverstonegraymetallic_tecnico_light_red_m": "uUFBcBeFKhE",
		"silverstonegraymetallic_tecnico_light_black_m": "Mcqw2ZBP_nA",
		"silverstonegraymetallic_tecnico_light_yellow_m": "JMtmOw-b6lg",
		"silverstonegraymetallic_5hole_dark_red_m": "sf8-Zg9WfwU",
		"silverstonegraymetallic_5hole_dark_black_m": "ljM6HWwjrYo",
		"silverstonegraymetallic_5hole_dark_yellow_m": "wjvQidzZSvo",
		"silverstonegraymetallic_5hole_light_red_m": "vAD7hjUQ-08",
		"silverstonegraymetallic_5hole_light_black_m": "hqwXsVzCIHM",
		"silverstonegraymetallic_5hole_light_yellow_m": "GW6nekQ5rM0",
		"vesuviograymetallic_tecnico_dark_red_m": "o6mhqp6vWj4",
		"vesuviograymetallic_tecnico_dark_black_m": "jMl9_6t91T4",
		"vesuviograymetallic_tecnico_dark_yellow_m": "SW_TKnEEKm8",
		"vesuviograymetallic_tecnico_light_red_m": "aVxX59sIvno",
		"vesuviograymetallic_tecnico_light_black_m": "bHe6SYYldiU",
		"vesuviograymetallic_tecnico_light_yellow_m": "jaiaUNw2yvo",
		"vesuviograymetallic_5hole_dark_red_m": "3GK9WLj4jig",
		"vesuviograymetallic_5hole_dark_black_m": "qo7ro6jxhjs",
		"vesuviograymetallic_5hole_dark_yellow_m": "Es6HxiS8sS0",
		"vesuviograymetallic_5hole_light_red_m": "64w4um9i0yE",
		"vesuviograymetallic_5hole_light_black_m": "5DaSHF944TA",
		"vesuviograymetallic_5hole_light_yellow_m": "ll9Ea6nFSF8",
		"vulcanoblackmetallic_tecnico_dark_red_m": "-CTjEp406DE",
		"vulcanoblackmetallic_tecnico_dark_black_m": "ORxpIsWxVW4",
		"vulcanoblackmetallic_tecnico_dark_yellow_m": "CpO9asE-ORk",
		"vulcanoblackmetallic_tecnico_light_red_m": "48Wc2A7g2KY",
		"vulcanoblackmetallic_tecnico_light_black_m": "k3iCRa7FPIE",
		"vulcanoblackmetallic_tecnico_light_yellow_m": "ekm826-BEgM",
		"vulcanoblackmetallic_5hole_dark_red_m": "Bih1AwBXE1M",
		"vulcanoblackmetallic_5hole_dark_black_m": "slwF34_xUUk",
		"vulcanoblackmetallic_5hole_dark_yellow_m": "ysjaAah9znQ",
		"vulcanoblackmetallic_5hole_light_red_m": "zT88525zqj8",
		"vulcanoblackmetallic_5hole_light_black_m": "7xfmcErrwX8",
		"vulcanoblackmetallic_5hole_light_yellow_m": "ais4GW-jYh4",
		"trofeowhitetricoat_tecnico_dark_red_m": "jj7Do-qC_as",
		"trofeowhitetricoat_tecnico_dark_black_m": "cpnqrkEYkpI",
		"trofeowhitetricoat_tecnico_dark_yellow_m": "l1WI84EBWyQ",
		"trofeowhitetricoat_tecnico_light_red_m": "HAD0C4XHo5U",
		"trofeowhitetricoat_tecnico_light_black_m": "nH-3RL1fLic",
		"trofeowhitetricoat_tecnico_light_yellow_m": "ikU-Xvr_zYc",
		"trofeowhitetricoat_5hole_dark_red_m": "UuUyhFc5_nc",
		"trofeowhitetricoat_5hole_dark_black_m": "FnxPKNJ688s",
		"trofeowhitetricoat_5hole_dark_yellow_m": "NXTn7CKi3XY",
		"trofeowhitetricoat_5hole_light_red_m": "Ly4y0_4ASD0",
		"trofeowhitetricoat_5hole_light_black_m": "p1NlOtVut80",
		"trofeowhitetricoat_5hole_light_yellow_m": "F2F190_hpdY",
		"rossocompetizionetricoat_tecnico_dark_red_m": "ty7T6VZxkvo",
		"rossocompetizionetricoat_tecnico_dark_black_m": "_IpL42zHYQg",
		"rossocompetizionetricoat_tecnico_dark_yellow_m": "G8WRQ9xIYok",
		"rossocompetizionetricoat_tecnico_light_red_m": "uAzN4V8z3YM",
		"rossocompetizionetricoat_tecnico_light_black_m": "8ofL53X2ySs",
		"rossocompetizionetricoat_tecnico_light_yellow_m": "oDsLSSNmCr8",
		"rossocompetizionetricoat_5hole_dark_red_m": "PiUc5JkLxBk",
		"rossocompetizionetricoat_5hole_dark_black_m": "w9r7kaKAX_Y",
		"rossocompetizionetricoat_5hole_dark_yellow_m": "QBi1jbvySa4",
		"rossocompetizionetricoat_5hole_light_red_m": "uQZ7GoMI9ss",
		"rossocompetizionetricoat_5hole_light_black_m": "YbXNZ7u3hKE",
		"rossocompetizionetricoat_5hole_light_yellow_m": "FKzYK4CFMtc",

	},

	"Files": {

		"launch_videos": [
			"90snoneinteractive"
		],
		"colorizer": [
			"rossoalfa",
			"silverstonegraymetallic",
			"vesuviograymetallic",
			"vulcanoblackmetallic",
			"montecarlobluemetallic",
			"trofeowhitetricoat",
			"rossocompetizionetricoat"
		],
		"colorizer_mobile": [
			"30snoneinteractive",
		],
		"deep_dives": {
			"splitter": [
				"splitter",
				"splitter_englishcallouts",
				"splitter_frenchcallouts",
				"splitter_italiancallouts",
				"splitter_germancallouts",
				"splitter_spanishcallouts"
			],
			"engine": [
				"engine",
				"engine_englishcallouts",
				"engine_frenchcallouts",
				"engine_italiancallouts",
				"engine_germancallouts",
				"engine_spanishcallouts"
			],

			"carbonfiber": [
				"carbonfiber",
				"carbonfiber_englishcallouts",
				"carbonfiber_frenchcallouts",
				"carbonfiber_italiancallouts",
				"carbonfiber_germancallouts",
				"carbonfiber_spanishcallouts"
			]
		},
		"deep_dives_mobile": {
			"splitter": [
				"splitter_englishcallout_m",
				"splitter_frenchcallout_m",
				"splitter_italiancallout_m",
				"splitter_germancallout_m",
				"splitter_spanishcallout_m",
			],
			"engine": [
				"engine_englishcallout_m",
				"engine_frenchcallout_m",
				"engine_italiancallout_m",
				"engine_germancallout_m",
				"engine_spanishcallout_m"
			],

			"carbonfiber": [
				"carbonfiber_englishcallout_m",
				"carbonfiber_frenchcallout_m",
				"carbonfiber_italiancallout_m",
				"carbonfiber_germancallout_m",
				"carbonfiber_spanishcallout_m"
			]
		},

		"visualizer": [
			"rossoalfa_tecnico_dark_red_day",
			"rossoalfa_tecnico_dark_red_night",
			"rossoalfa_tecnico_dark_black_day",
			"rossoalfa_tecnico_dark_black_night",
			"rossoalfa_tecnico_dark_yellow_day",
			"rossoalfa_tecnico_dark_yellow_night",
			"rossoalfa_tecnico_light_red_day",
			"rossoalfa_tecnico_light_red_night",
			"rossoalfa_tecnico_light_black_day",
			"rossoalfa_tecnico_light_black_night",
			"rossoalfa_tecnico_light_yellow_day",
			"rossoalfa_tecnico_light_yellow_night",
			"rossoalfa_5hole_dark_red_day",
			"rossoalfa_5hole_dark_red_night",
			"rossoalfa_5hole_dark_black_day",
			"rossoalfa_5hole_dark_black_night",
			"rossoalfa_5hole_dark_yellow_day",
			"rossoalfa_5hole_dark_yellow_night",
			"rossoalfa_5hole_light_red_day",
			"rossoalfa_5hole_light_red_night",
			"rossoalfa_5hole_light_black_day",
			"rossoalfa_5hole_light_black_night",
			"rossoalfa_5hole_light_yellow_day",
			"rossoalfa_5hole_light_yellow_night",
			"montecarlobluemetallic_tecnico_dark_red_day",
			"montecarlobluemetallic_tecnico_dark_red_night",
			"montecarlobluemetallic_tecnico_dark_black_day",
			"montecarlobluemetallic_tecnico_dark_black_night",
			"montecarlobluemetallic_tecnico_dark_yellow_day",
			"montecarlobluemetallic_tecnico_dark_yellow_night",
			"montecarlobluemetallic_tecnico_light_red_day",
			"montecarlobluemetallic_tecnico_light_red_night",
			"montecarlobluemetallic_tecnico_light_black_day",
			"montecarlobluemetallic_tecnico_light_black_night",
			"montecarlobluemetallic_tecnico_light_yellow_day",
			"montecarlobluemetallic_tecnico_light_yellow_night",
			"montecarlobluemetallic_5hole_dark_red_day",
			"montecarlobluemetallic_5hole_dark_red_night",
			"montecarlobluemetallic_5hole_dark_black_day",
			"montecarlobluemetallic_5hole_dark_black_night",
			"montecarlobluemetallic_5hole_dark_yellow_day",
			"montecarlobluemetallic_5hole_dark_yellow_night",
			"montecarlobluemetallic_5hole_light_red_day",
			"montecarlobluemetallic_5hole_light_red_night",
			"montecarlobluemetallic_5hole_light_black_day",
			"montecarlobluemetallic_5hole_light_black_night",
			"montecarlobluemetallic_5hole_light_yellow_day",
			"montecarlobluemetallic_5hole_light_yellow_night",
			"silverstonegraymetallic_tecnico_dark_red_day",
			"silverstonegraymetallic_tecnico_dark_red_night",
			"silverstonegraymetallic_tecnico_dark_black_day",
			"silverstonegraymetallic_tecnico_dark_black_night",
			"silverstonegraymetallic_tecnico_dark_yellow_day",
			"silverstonegraymetallic_tecnico_dark_yellow_night",
			"silverstonegraymetallic_tecnico_light_red_day",
			"silverstonegraymetallic_tecnico_light_red_night",
			"silverstonegraymetallic_tecnico_light_black_day",
			"silverstonegraymetallic_tecnico_light_black_night",
			"silverstonegraymetallic_tecnico_light_yellow_day",
			"silverstonegraymetallic_tecnico_light_yellow_night",
			"silverstonegraymetallic_5hole_dark_red_day",
			"silverstonegraymetallic_5hole_dark_red_night",
			"silverstonegraymetallic_5hole_dark_black_day",
			"silverstonegraymetallic_5hole_dark_black_night",
			"silverstonegraymetallic_5hole_dark_yellow_day",
			"silverstonegraymetallic_5hole_dark_yellow_night",
			"silverstonegraymetallic_5hole_light_red_day",
			"silverstonegraymetallic_5hole_light_red_night",
			"silverstonegraymetallic_5hole_light_black_day",
			"silverstonegraymetallic_5hole_light_black_night",
			"silverstonegraymetallic_5hole_light_yellow_day",
			"silverstonegraymetallic_5hole_light_yellow_night",
			"vesuviograymetallic_tecnico_dark_red_day",
			"vesuviograymetallic_tecnico_dark_red_night",
			"vesuviograymetallic_tecnico_dark_black_day",
			"vesuviograymetallic_tecnico_dark_black_night",
			"vesuviograymetallic_tecnico_dark_yellow_day",
			"vesuviograymetallic_tecnico_dark_yellow_night",
			"vesuviograymetallic_tecnico_light_red_day",
			"vesuviograymetallic_tecnico_light_red_night",
			"vesuviograymetallic_tecnico_light_black_day",
			"vesuviograymetallic_tecnico_light_black_night",
			"vesuviograymetallic_tecnico_light_yellow_day",
			"vesuviograymetallic_tecnico_light_yellow_night",
			"vesuviograymetallic_5hole_dark_red_day",
			"vesuviograymetallic_5hole_dark_red_night",
			"vesuviograymetallic_5hole_dark_black_day",
			"vesuviograymetallic_5hole_dark_black_night",
			"vesuviograymetallic_5hole_dark_yellow_day",
			"vesuviograymetallic_5hole_dark_yellow_night",
			"vesuviograymetallic_5hole_light_red_day",
			"vesuviograymetallic_5hole_light_red_night",
			"vesuviograymetallic_5hole_light_black_day",
			"vesuviograymetallic_5hole_light_black_night",
			"vesuviograymetallic_5hole_light_yellow_day",
			"vesuviograymetallic_5hole_light_yellow_night",
			"vulcanoblackmetallic_tecnico_dark_red_day",
			"vulcanoblackmetallic_tecnico_dark_red_night",
			"vulcanoblackmetallic_tecnico_dark_black_day",
			"vulcanoblackmetallic_tecnico_dark_black_night",
			"vulcanoblackmetallic_tecnico_dark_yellow_day",
			"vulcanoblackmetallic_tecnico_dark_yellow_night",
			"vulcanoblackmetallic_tecnico_light_red_day",
			"vulcanoblackmetallic_tecnico_light_red_night",
			"vulcanoblackmetallic_tecnico_light_black_day",
			"vulcanoblackmetallic_tecnico_light_black_night",
			"vulcanoblackmetallic_tecnico_light_yellow_day",
			"vulcanoblackmetallic_tecnico_light_yellow_night",
			"vulcanoblackmetallic_5hole_dark_red_day",
			"vulcanoblackmetallic_5hole_dark_red_night",
			"vulcanoblackmetallic_5hole_dark_black_day",
			"vulcanoblackmetallic_5hole_dark_black_night",
			"vulcanoblackmetallic_5hole_dark_yellow_day",
			"vulcanoblackmetallic_5hole_dark_yellow_night",
			"vulcanoblackmetallic_5hole_light_red_day",
			"vulcanoblackmetallic_5hole_light_red_night",
			"vulcanoblackmetallic_5hole_light_black_day",
			"vulcanoblackmetallic_5hole_light_black_night",
			"vulcanoblackmetallic_5hole_light_yellow_day",
			"vulcanoblackmetallic_5hole_light_yellow_night",
			"trofeowhitetricoat_tecnico_dark_red_day",
			"trofeowhitetricoat_tecnico_dark_red_night",
			"trofeowhitetricoat_tecnico_dark_black_day",
			"trofeowhitetricoat_tecnico_dark_black_night",
			"trofeowhitetricoat_tecnico_dark_yellow_day",
			"trofeowhitetricoat_tecnico_dark_yellow_night",
			"trofeowhitetricoat_tecnico_light_red_day",
			"trofeowhitetricoat_tecnico_light_red_night",
			"trofeowhitetricoat_tecnico_light_black_day",
			"trofeowhitetricoat_tecnico_light_black_night",
			"trofeowhitetricoat_tecnico_light_yellow_day",
			"trofeowhitetricoat_tecnico_light_yellow_night",
			"trofeowhitetricoat_5hole_dark_red_day",
			"trofeowhitetricoat_5hole_dark_red_night",
			"trofeowhitetricoat_5hole_dark_black_day",
			"trofeowhitetricoat_5hole_dark_black_night",
			"trofeowhitetricoat_5hole_dark_yellow_day",
			"trofeowhitetricoat_5hole_dark_yellow_night",
			"trofeowhitetricoat_5hole_light_red_day",
			"trofeowhitetricoat_5hole_light_red_night",
			"trofeowhitetricoat_5hole_light_black_day",
			"trofeowhitetricoat_5hole_light_black_night",
			"trofeowhitetricoat_5hole_light_yellow_day",
			"trofeowhitetricoat_5hole_light_yellow_night",
			"rossocompetizionetricoat_tecnico_dark_red_day",
			"rossocompetizionetricoat_tecnico_dark_red_night",
			"rossocompetizionetricoat_tecnico_dark_black_day",
			"rossocompetizionetricoat_tecnico_dark_black_night",
			"rossocompetizionetricoat_tecnico_dark_yellow_day",
			"rossocompetizionetricoat_tecnico_dark_yellow_night",
			"rossocompetizionetricoat_tecnico_light_red_day",
			"rossocompetizionetricoat_tecnico_light_red_night",
			"rossocompetizionetricoat_tecnico_light_black_day",
			"rossocompetizionetricoat_tecnico_light_black_night",
			"rossocompetizionetricoat_tecnico_light_yellow_day",
			"rossocompetizionetricoat_tecnico_light_yellow_night",
			"rossocompetizionetricoat_5hole_dark_red_day",
			"rossocompetizionetricoat_5hole_dark_red_night",
			"rossocompetizionetricoat_5hole_dark_black_day",
			"rossocompetizionetricoat_5hole_dark_black_night",
			"rossocompetizionetricoat_5hole_dark_yellow_day",
			"rossocompetizionetricoat_5hole_dark_yellow_night",
			"rossocompetizionetricoat_5hole_light_red_day",
			"rossocompetizionetricoat_5hole_light_red_night",
			"rossocompetizionetricoat_5hole_light_black_day",
			"rossocompetizionetricoat_5hole_light_black_night",
			"rossocompetizionetricoat_5hole_light_yellow_day",
			"rossocompetizionetricoat_5hole_light_yellow_night"
		],
		"visualizer_mobile": [
			"rossoalfa_tecnico_dark_red_m",
			"rossoalfa_tecnico_dark_black_m",
			"rossoalfa_tecnico_dark_yellow_m",
			"rossoalfa_tecnico_light_red_m",
			"rossoalfa_tecnico_light_black_m",
			"rossoalfa_tecnico_light_yellow_m",
			"rossoalfa_5hole_dark_red_m",
			"rossoalfa_5hole_dark_black_m",
			"rossoalfa_5hole_dark_yellow_m",
			"rossoalfa_5hole_light_red_m",
			"rossoalfa_5hole_light_black_m",
			"rossoalfa_5hole_light_yellow_m",
			"montecarlobluemetallic_tecnico_dark_red_m",
			"montecarlobluemetallic_tecnico_dark_black_m",
			"montecarlobluemetallic_tecnico_dark_yellow_m",
			"montecarlobluemetallic_tecnico_light_red_m",
			"montecarlobluemetallic_tecnico_light_black_m",
			"montecarlobluemetallic_tecnico_light_yellow_m",
			"montecarlobluemetallic_5hole_dark_red_m",
			"montecarlobluemetallic_5hole_dark_black_m",
			"montecarlobluemetallic_5hole_dark_yellow_m",
			"montecarlobluemetallic_5hole_light_red_m",
			"montecarlobluemetallic_5hole_light_black_m",
			"montecarlobluemetallic_5hole_light_yellow_m",
			"silverstonegraymetallic_tecnico_dark_red_m",
			"silverstonegraymetallic_tecnico_dark_black_m",
			"silverstonegraymetallic_tecnico_dark_yellow_m",
			"silverstonegraymetallic_tecnico_light_red_m",
			"silverstonegraymetallic_tecnico_light_black_m",
			"silverstonegraymetallic_tecnico_light_yellow_m",
			"silverstonegraymetallic_5hole_dark_red_m",
			"silverstonegraymetallic_5hole_dark_black_m",
			"silverstonegraymetallic_5hole_dark_yellow_m",
			"silverstonegraymetallic_5hole_light_red_m",
			"silverstonegraymetallic_5hole_light_black_m",
			"silverstonegraymetallic_5hole_light_yellow_m",
			"vesuviograymetallic_tecnico_dark_red_m",
			"vesuviograymetallic_tecnico_dark_black_m",
			"vesuviograymetallic_tecnico_dark_yellow_m",
			"vesuviograymetallic_tecnico_light_red_m",
			"vesuviograymetallic_tecnico_light_black_m",
			"vesuviograymetallic_tecnico_light_yellow_m",
			"vesuviograymetallic_5hole_dark_red_m",
			"vesuviograymetallic_5hole_dark_black_m",
			"vesuviograymetallic_5hole_dark_yellow_m",
			"vesuviograymetallic_5hole_light_red_m",
			"vesuviograymetallic_5hole_light_black_m",
			"vesuviograymetallic_5hole_light_yellow_m",
			"vulcanoblackmetallic_tecnico_dark_red_m",
			"vulcanoblackmetallic_tecnico_dark_black_m",
			"vulcanoblackmetallic_tecnico_dark_yellow_m",
			"vulcanoblackmetallic_tecnico_light_red_m",
			"vulcanoblackmetallic_tecnico_light_black_m",
			"vulcanoblackmetallic_tecnico_light_yellow_m",
			"vulcanoblackmetallic_5hole_dark_red_m",
			"vulcanoblackmetallic_5hole_dark_black_m",
			"vulcanoblackmetallic_5hole_dark_yellow_m",
			"vulcanoblackmetallic_5hole_light_red_m",
			"vulcanoblackmetallic_5hole_light_black_m",
			"vulcanoblackmetallic_5hole_light_yellow_m",
			"trofeowhitetricoat_tecnico_dark_red_m",
			"trofeowhitetricoat_tecnico_dark_black_m",
			"trofeowhitetricoat_tecnico_dark_yellow_m",
			"trofeowhitetricoat_tecnico_light_red_m",
			"trofeowhitetricoat_tecnico_light_black_m",
			"trofeowhitetricoat_tecnico_light_yellow_m",
			"trofeowhitetricoat_5hole_dark_red_m",
			"trofeowhitetricoat_5hole_dark_black_m",
			"trofeowhitetricoat_5hole_dark_yellow_m",
			"trofeowhitetricoat_5hole_light_red_m",
			"trofeowhitetricoat_5hole_light_black_m",
			"trofeowhitetricoat_5hole_light_yellow_m",
			"rossocompetizionetricoat_tecnico_dark_red_m",
			"rossocompetizionetricoat_tecnico_dark_black_m",
			"rossocompetizionetricoat_tecnico_dark_yellow_m",
			"rossocompetizionetricoat_tecnico_light_red_m",
			"rossocompetizionetricoat_tecnico_light_black_m",
			"rossocompetizionetricoat_tecnico_light_yellow_m",
			"rossocompetizionetricoat_5hole_dark_red_m",
			"rossocompetizionetricoat_5hole_dark_black_m",
			"rossocompetizionetricoat_5hole_dark_yellow_m",
			"rossocompetizionetricoat_5hole_light_red_m",
			"rossocompetizionetricoat_5hole_light_black_m",
			"rossocompetizionetricoat_5hole_light_yellow_m",

		]
	}
}


// var csv_to_hash = function(csv)
// {
// 	// var d = CONFIG.files[type];
// 	var lines = csv.split("\n");
// 	var type = '';

// 	var results = {};

// 	for(var i in lines)
// 	{
// 		var line = lines[i];

// 		if(line.indexOf(':') === 0)
// 		{
// 			type = line.slice(1).trim().toLowerCase;
// 			continue;
// 		}

// 		var parts = line.split(',');

// 		var filename = parts[0];
// 		var video_id = parts[1];

// 		results[filename] = video_id;

// 		return results;
// 	}

// 	console.log()

// }